public class Main {
    public static void main(String[] args) {
        // Création d'une ambulance
        Ambulance ambulance = new Ambulance(29600000, 4, 2,1800, 12, "Carrier Bed Vehicle", "DPS", 13);
        System.out.println("\n\t [1] CALCULATION OF THE AMBULANCE TAXES" + "\n\t\t [*] THE INFORMATIONS ATTACHED TO THE AMBULANCE CAR ARE : " + "\n\t\t\t The Coast Insurance Freight is : " + ambulance.CIF + " UGX" + "\n\t\t\t The Seating Capacity is        : " + ambulance.Seating_Capacity + "  Places" + "\n\t\t\t The Gross Weight is            : " + ambulance.Gross_Weight + "  Tonnes" + "\n\t\t\t The Engine Capacity is         : " + ambulance.Engine_Capacity + "  CC" + "\n\t\t\t The Ambulance age is           : " + ambulance.Age +  "  Years" + "\n\t\t\t The Mode of transportation is  : " + ambulance.Transportation_Mode + "\n\t\t\t The Plate System is            : " + ambulance.Plate_System + "\n\t\t\t The Storage Duration is        : " + ambulance.Storage_Days + " Days" + "\n\n\t\t [*] TAXES FOR THE AMBULANCE ARE " + "\n\t\t\t THE INFRASTRUCTURE LEVY IS : " + 150000 + " UGX" + "\n\t\t\t THE STAMP DUTY IS          : " + 35000 + "  UGX" + "\n\t\t\t THE FORM FEES IS           : " + 20000 + "  UGX" + "\n\t\t\t THE EXCISE DUTY IS         : " + 200000 + " UGX" + "\n\t\t\t THE REGISTRATION IS        : " + ambulance.Registration + " UGX" + "\n\t\t -----------------------------------------------------------" + "\n\t\t [#] ==> THE TOTAL TAXES FOR THE AMBULANCE IS : " + ambulance.Compute_Taxes() + " UGX" + "\n\t\t -----------------------------------------------------------");

        // Création d'une voiture Estate
        Estate estate = new Estate(55500000, 5, 1.5, 1900, 2, "Carrier Bed Vehicle", "APS", 13); // (APS = Analog Plate Systems (DPS = Digital Plate Systems)
        System.out.println("\n\t [2] CALCULATION OF THE ESTATE CAR TAXES" + "\n\t\t [*] THE INFORMATIONS ATTACHED TO THE ESTATE CAR ARE : " + "\n\t\t\t The Coast Insurance Freight is : " + estate.CIF + " UGX" + "\n\t\t\t The Seating Capacity is        : " + estate.Seating_Capacity + "  Places" + "\n\t\t\t The Gross Weight is            : " + estate.Gross_Weight + "  Tonnes" + "\n\t\t\t The Engine Capacity is         : " + estate.Engine_Capacity + "  CC" + "\n\t\t\t The Ambulance age is           : " + estate.Age +  "  Years" + "\n\t\t\t The Mode of transportation is  : " + estate.Transportation_Mode + "\n\t\t\t The Plate System is            : " + estate.Plate_System + "\n\t\t\t The Storage Duration is        : " + estate.Storage_Days + " Days" + "\n\n\t\t [*] TAXES FOR THE AMBULANCE ARE " + "\n\t\t\t THE IMPORT DUTY IS         : " + (estate.CIF*0.25) + " UGX" + "\n\t\t\t THE VALUE ADDED TAX IS     : " + (estate.CIF*0.18) + " UGX" + "\n\t\t\t THE WITHHOLDING TAX IS     : " + (estate.CIF*0.06) + " UGX" + "\n\t\t\t THE INFRASTRUCTURE LEVY IS : " + 150000 + " UGX" + "\n\t\t\t THE STAMP DUTY IS          : " + 35000 + "  UGX" + "\n\t\t\t THE FORM FEES IS           : " + 20000 + "  UGX" + "\n\t\t\t THE EXCISE DUTY IS         : " + 200000 + " UGX" + "\n\t\t\t THE REGISTRATION IS        : " + estate.Registration + " UGX" + "\n\t\t ---------------------------------------------------------" + "\n\t\t [#] THE TOTAL TAXE FOR THE ESTATE CAR IS : " + estate.Compute_Taxes() + " UGX" + "\n\t\t ---------------------------------------------------------");

        // Création d'un SUV
        SUV suv = new SUV(62000000, 5, 2.5,1800, 5, "Carrier Bed Vehicle", "DPS", 13);
        System.out.println("\n\t [3] CALCULATION OF THE SUV CAR TAXES" + "\n\t\t [*] THE INFORMATIONS ATTACHED TO THE SUV CAR ARE : " + "\n\t\t\t The Coast Insurance Freight is : " + suv.CIF + " UGX" + "\n\t\t\t The Seating Capacity is        : " + suv.Seating_Capacity + "  Places" + "\n\t\t\t The Gross Weight is            : " + suv.Gross_Weight + "  Tonnes" + "\n\t\t\t The Engine Capacity is         : " + suv.Engine_Capacity + "  CC" + "\n\t\t\t The Ambulance age is           : " + suv.Age +  "  Years" + "\n\t\t\t The Mode of transportation is  : " + suv.Transportation_Mode + "\n\t\t\t The Plate System is            : " + suv.Plate_System + "\n\t\t\t The Storage Duration is        : " + suv.Storage_Days + " Days" + "\n\n\t\t [*] TAXES FOR THE AMBULANCE ARE " + "\n\t\t\t THE IMPORT DUTY IS         : " + (suv.CIF*0.25) + " UGX" + "\n\t\t\t THE VALUE ADDED TAX IS     : " + (suv.CIF*0.18) + " UGX" + "\n\t\t\t THE WITHHOLDING TAX IS     : " + (suv.CIF*0.06) + " UGX" + "\n\t\t\t THE INFRASTRUCTURE LEVY IS : " + 150000 + " UGX" + "\n\t\t\t THE STAMP DUTY IS          : " + 35000 + "  UGX" + "\n\t\t\t THE FORM FEES IS           : " + 20000 + "  UGX" + "\n\t\t\t THE EXCISE DUTY IS         : " + 200000 + " UGX" + "\n\t\t\t THE REGISTRATION IS        : " + suv.Registration + " UGX" + "\n\t\t ---------------------------------------------------------" + "\n\t\t [#] THE TOTAL TAXES FOR THE SUV CAR IS : " + suv.Compute_Taxes() + " UGX" + "\n\t\t ---------------------------------------------------------");

        // Création d'une Trailer
        Trailer trailer = new Trailer(15000, 5, 1.8, 1800, 10, "Carrier Bed Vehicle", "APS", 13);
        System.out.println("\n\t [4] CALCULATION OF THE TRAILER CAR TAXES" + "\n\t\t [*] THE INFORMATIONS ATTACHED TO THE TRAILER CAR ARE : " + "\n\t\t\t The Coast Insurance Freight is : " + trailer.CIF + " UGX" + "\n\t\t\t The Seating Capacity is        : " + trailer.Seating_Capacity + "  Places" + "\n\t\t\t The Gross Weight is            : " + trailer.Gross_Weight + "  Tonnes" + "\n\t\t\t The Engine Capacity is         : " + trailer.Engine_Capacity + "  CC" + "\n\t\t\t The Ambulance age is           : " + trailer.Age +  "  Years" + "\n\t\t\t The Mode of transportation is  : " + trailer.Transportation_Mode + "\n\t\t\t The Plate System is            : " + trailer.Plate_System + "\n\t\t\t The Storage Duration is        : " + trailer.Storage_Days + " Days" + "\n\n\t\t [*] TAXES FOR THE AMBULANCE ARE " + "\n\t\t\t THE IMPORT DUTY IS         : " + (trailer.CIF*0.25) + " UGX" + "\n\t\t\t THE VALUE ADDED TAX IS     : " + (trailer.CIF*0.18) + " UGX" + "\n\t\t\t THE WITHHOLDING TAX IS     : " + (trailer.CIF*0.06) + " UGX" + "\n\t\t\t THE INFRASTRUCTURE LEVY IS : " + 150000 + " UGX" + "\n\t\t\t THE STAMP DUTY IS          : " + 35000 + "  UGX" + "\n\t\t\t THE FORM FEES IS           : " + 20000 + "  UGX" + "\n\t\t\t THE EXCISE DUTY IS         : " + 200000 + " UGX" + "\n\t\t\t THE REGISTRATION IS        : " + trailer.Registration + " UGX" + "\n\t\t ---------------------------------------------------------" + "\n\t\t [#] THE TOTAL TAXES FOR THE TRAILER CAR IS : " + trailer.Compute_Taxes() + " UGX" + "\n\t\t ---------------------------------------------------------");

        AnyOtherCar anyOtherCar = new AnyOtherCar(19000000, 4, 2.6, 11000, 4, "Driven", "DPS", 15);
        System.out.println("\n\t [5] CALCULATION OF TAXES FOR AN OTHER TYPE OF CAR" + "\n\t\t [*] THE INFORMATIONS ATTACHED TO THE OTHER TYPE OF CAR ARE : " + "\n\t\t\t The Coast Insurance Freight is : " + anyOtherCar.CIF + " UGX" + "\n\t\t\t The Seating Capacity is        : " + anyOtherCar.Seating_Capacity + "  Places" + "\n\t\t\t The Gross Weight is            : " + anyOtherCar.Gross_Weight + "  Tonnes" + "\n\t\t\t The Engine Capacity is         : " + anyOtherCar.Engine_Capacity + "  CC" + "\n\t\t\t The Ambulance age is           : " + anyOtherCar.Age +  "  Years" + "\n\t\t\t The Mode of transportation is  : " + anyOtherCar.Transportation_Mode + "\n\t\t\t The Plate System is            : " + anyOtherCar.Plate_System + "\n\t\t\t The Storage Duration is        : " + anyOtherCar.Storage_Days + " Days" + "\n\n\t\t [*] TAXES FOR THE AMBULANCE ARE " + "\n\t\t\t THE IMPORT DUTY IS         : " + (anyOtherCar.CIF*0.25) + " UGX" + "\n\t\t\t THE VALUE ADDED TAX IS     : " + (anyOtherCar.CIF*0.18) + " UGX" + "\n\t\t\t THE WITHHOLDING TAX IS     : " + (anyOtherCar.CIF*0.06) + " UGX" + "\n\t\t\t THE INFRASTRUCTURE LEVY IS : " + 150000 + " UGX" + "\n\t\t\t THE STAMP DUTY IS          : " + 35000 + "  UGX" + "\n\t\t\t THE FORM FEES IS           : " + 20000 + "  UGX" + "\n\t\t\t THE EXCISE DUTY IS         : " + 200000 + " UGX" + "\n\t\t\t THE REGISTRATION IS        : " + anyOtherCar.Registration + " UGX" + "\n\t\t ---------------------------------------------------------" + "\n\t\t [#] THE TOTAL TAXES FOR THE TRAILER CAR IS : " + trailer.Compute_Taxes() + " UGX" + "\n\t\t ---------------------------------------------------------");
    }
}